language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

install: composer install --no-interaction --prefer-dist --no-suggest --optimize-autoloader

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always
